### ISSUE TITLE
How to use retrier inside class function with custom on_retry?

### ISSUE THREAD

**Issue by dofine** [h2non/riprova#13]
Hi, I'd like to use `riprova.Retrier` inside my custom class. e.g. I want to try to re-login every time `say_trier` fails or raises an exception. Is this sample code right? Didn't find a nice way to use decorater for `say_trier`.

```python

class SayHello(object):
    def login(self):
        print "log in"
        do_login_process()

    def say(self):
        retrier = riprova.Retrier(backoff=riprova.ExponentialBackOff(interval=30), on_retry=self.on_retry)
        retrier.run(self.say_trier)

    def say_trier(self):
        something_may_fail_here()

    def on_retry(self, err, next_try):
        print('Operation error: {}'.format(err))
        print('Next try in: {}ms'.format(next_try))
        self.login()

sa = SayHello()
sa.say()
```

**Comment by tomas-fp** [comment]
Why not just?:
```python
class SayHello(object):
    def login(self):
        print "log in"
        do_login_process()

    def say(self):
        retrier = riprova.Retrier(backoff=riprova.ExponentialBackOff(interval=30), on_retry=self.on_retry)
        retrier.run(self.say_trier)

    def say_trier(self):
        self.login()
        something_may_fail_here()

    def on_retry(self, err, next_try):
        print('Operation error: {}'.format(err))
        print('Next try in: {}ms'.format(next_try))
```

**Comment by dofine** [comment]
@tomas-fp Thanks for your reply! I'm still learning about Python object-oriented programming.
But here `login` may take a long time. In your example, every time `say` runs it'll trigger `login`? I just want to do `login` only if `say` fails. (suppose that `login` never fails.)

**Comment by tomas-fp** [comment]
You can manage the login logic in the `login` method.

**Comment by tomas-fp** [comment]
And then decide there whether if you need to perform a login or not, so that way you would prevent extra login attempts. You can do that by checking if the user login token session is still working or it may expired. Does it make sense?

**Comment by dofine** [comment]
@tomas-fp Thanks! I'll try and work with it!
