### ISSUE TITLE
Retrier catches internal error

### ISSUE THREAD

**Issue by tsarpaul** [h2non/riprova#6]
```self.error = err

 # Get delay before next retry
 delay = self.backoff.next()

 # If backoff is ready
 if delay == Backoff.STOP:
 return raise_from(MaxRetriesExceeded('max retries exceeded'), err)
```

While messing around with the code I checked err value and was surprised to see ImportError:

> err = {ImportError} No module named stackless

The error was PyCharm related, maybe a similar error would be caused if I forgot to pip install requirements?

This code ignores all errors, even if it is caused internally and not by the function.

A possible solution is to blacklist certain errors, such as ImportError

**Comment by h2non** [comment]
That sounds reasonable, since it's a common premise. I've in mind supporting a custom evaluator function that would determine when an exception is legit or not.
I think I can support it later today.

**Comment by h2non** [comment]
I've introduced support for whitelisted errors and custom error evaluator function.

See implementation details here:
https://github.com/h2non/riprova/commit/3fcde036199f582656f03eb017aba770ff5215a1

This would be available in `riprova@0.1.3` soon.

**Comment by tsarpaul** [comment]
Not sure if you get notified, left you a comment on one deletion.

**Comment by h2non** [comment]
`riprova@0.1.3` now supports custom error evaluator logic and whitelisting/blacklisting errors.

For usage examples, see:
https://github.com/h2non/riprova/blob/master/examples/blacklisting_errors.py
https://github.com/h2non/riprova/blob/master/examples/whitelisting_errors.py

You can upgrade `riprova` simply running:
```bash
pip install -U riprova
```

Closing issue.
