### ISSUE TITLE
Bug | Inconsistent test

### ISSUE THREAD

**Issue by tsarpaul** [h2non/riprova#7]
timeout = 200 while interval=100 causes the target function to run either twice or thrice (due to machine speed), which makes the following test inconsistent:
```
def test_retrier_run_max_timeout(MagicMock):
    iterable = (ValueError, NotImplementedError, RuntimeError, Exception)
    task = MagicMock(side_effect=iterable)

    retrier = Retrier(timeout=200, backoff=ConstantBackoff(interval=100))

    with pytest.raises(RetryTimeoutError):
        retrier.run(task, 2, 4, foo='bar')

    assert task.called
    assert task.call_count >= 1
    task.assert_called_with(2, 4, foo='bar')

    assert retrier.attempts >= 1
    assert isinstance(retrier.error, NotImplementedError)
```

Sometimes the raised error would be NotImplementedError, while at other times RunTimeError

I changed this test in my pull request  but the core problem needs to be fixed.

**Comment by h2non** [comment]
This is the never ending story while relying on timers, which are not 100%  accurate and would depend on OS CPU scheduling, however while running synchronous code the accuracy level should be almost exact in most cases.

I personally didn't experience the issue, but the test case could simply use the same exception type.

**Comment by h2non** [comment]
@tsarpaul By the way, thank you for the PR.

**Comment by tsarpaul** [comment]
Then perhaps use a counter which goes up to timeout/interval then times out on timeout/interval + 1?
I tested this case a little and around 30% of the times I had 3 iterations over expected 2.

**Comment by h2non** [comment]
This should be fixed. I'm going to close this for now.
