### ISSUE TITLE
Retry context manager

### ISSUE THREAD

**Issue by tomas-fp** [h2non/riprova#9]
```python
with riprova.Retrier(backoff=ConstantBackoff()) as retry:
   retry.run(run_failed_task, 'foo', bar=1)

async with riprova.AsyncRetrier(backoff=ConstantBackoff()) as retry:
   await retry.run(run_failed_task, 'foo', bar=1)
```

**Comment by pohmelie** [comment]
What purpose of context manager here? I mean, what will you finalize in `__exit__`/`__aexit__`?

**Comment by h2non** [comment]
Shipped in `v0.2.0`. Closing.

**Comment by pohmelie** [comment]
Still don't get why we need context manager if it just reraise exception? https://github.com/h2non/riprova/blob/master/riprova/retrier.py#L312

**Comment by h2non** [comment]
You're totally right.
